### PR TITLE
Add support for PyYAML v5 #1

### PR DESCRIPTION
**Pull request by pombredanne**
* This is a fix for #1 to support both PyYAML 3.1x and the newer PyYAML 5.1.x
  Several subtle changes had been introduced and this resolves them all.

* The PyYAML version constraint has been entirely removed from setup.py

* CI testing has been enabled on Appveyor/WIndows an Travis/Linux 

Reported-by: Dan Kegel <dank@kegel.com>
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by pombredanne** [comment]
@dankegel ping. Do you mind testing this in your config?

**Comment by pombredanne** [comment]
@dankegel I also tagged and pushed a release 0.4 https://pypi.org/project/saneyaml/0.4/

**Comment by dankegel** [comment]
I installed https://launchpad.net/~dank/+archive/ubuntu/python-fixes to work around the nastier problems in the system pip + python ecosystem, then ran 'pip install scancode-toolkit; scancode --version' across my fleet.

I can still see the original problem like this:
```
$ rm -rf ~/.local
$ pip install scancode-toolkit
$ scancode --version
ScanCode version 3.0.2
$ pip list | grep -i pyyaml
PyYAML (3.13)
$ pip install PyYaml==5.1
$ scancode --version
pluggy.manager.PluginValidationError: Plugin 'json-pp' could not be loaded: (PyYAML 5.1 (/home/buildbot/.local/lib/python2.7/site-packages), Requirement.parse('PyYAML<=3.13,>=3.11'))!
```

I'm a bit dense, though, since that's probably expected until scancode drops its own strict
PyYAML dependency...

Incidentally, I learned that pip 8.1 at least seems to lie when you ask it to uninstall things; it leaves
behind foo-x.y.dist-info directories that confuse things.  So when troubleshooting, rm -rf ~/.local (or, more sanely, mv ~/.local ~/.local.bad) is crucial for figuring out wtf is going on.

**Comment by jelmer** [comment]
Any news on this?

**Comment by pombredanne** [comment]
@jelmer let me merge this and push a few new updates. Thanks for the reminder!

**Pull request merged**
